license_id: cc-by-igo
methodology: Other
methodology_other: Please find the methodology at [this link](https://www.ncei.noaa.gov/sites/g/files/anmtlf171/files/2024-07/IBTrACS_version4r01_Technical_Details.pdf)
caveats: "Some early (pre-1950) storms were not correctly matched, so the number of storms in the record is artificially high. For example, SIO storms in 1901 are not matched, so the same storm is tracked by the following identifiers: ds824, td9636, and reunion. This storm is broken into different tracks because of temporal differences in the storm data."
dataset_source: National Oceanic and Atmospheric Administration (NOAA) / National Centers for Environmental Information (NCEI)
package_creator: HDX Data Systems Team
private: False
maintainer: 2f9fd160-2a16-49c0-89d6-0bc3230599bf
owner_org:  hdx
notes: "The International Best Track Archive for Climate Stewardship (IBTrACS) project is the most complete global collection of tropical cyclones available. It merges recent and historical tropical cyclone data from multiple agencies to create a unified, publicly available, best-track dataset that improves inter-agency comparisons. \n
\n Fields available: \n
SID: A unique storm identifier (SID) assigned by IBTrACS algorithm.\n
ISO_TIME: Time of the observation in ISO format (YYYY-MM-DD hh:mm:ss) \n
BASIN: Basin of the current storm position \n
SUBBASIN: Sub-basin of the current storm position \n
NATURE: Type of storm (a combination of the various types from the available sources) \n
NUMBER: Number of the storm for the year (restarts at 1 for each year \n
LAT: Mean position - latitude (a combination of the available positions) \n
LON: Mean position - longitude (a combination of the available positions) \n
WMO_WIND: Maximum sustained wind speed assigned by the responsible WMO agency \n
WMO_PRES: Minimum central pressure assigned by the responsible WMO agency."
subnational: "0"
